config/routes.rb
TodoBackboneRails::Application.routes.draw do
  namespace :api do
    resources :lists, only: [] do
      resources :todos, only: [:index, :create, :show, :update, :destroy]
    end 
  end

  resources :lists, only: [:create, :show]

  root to: 'lists#new'

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list
end

app/controllers/api/todos_controller.rb
class Api::TodosController < ApplicationController
  before_filter :find_list, :random_slowdown

  respond_to :json

  # GET /api/lists/:list_id/todos
  def index
    respond_with @list.todos
  end

  # POST /api/lists/:list_id/todos
  def create
    respond_with :api, @list, @list.todos.create!(todo_params)
  end

  # GET /api/lists/:list_id/todos/:id
  def show
    respond_with @list.todos.find(params[:id])
  end

  # PUT/PATCH /api/lists/:list_id/todos/:id
  def update
    respond_with :api, @list, @list.todos.find(params[:id]).update_attributes!(todo_params)
  end

  # DELETE /api/lists/:list_id/todos/:id
  def destroy
    respond_with :api, @list, @list.todos.find(params[:id]).destroy!
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  # Randomly pause for somewhere between 0-2 seconds
  def random_slowdown
    sleep rand(0..2000) / 1000.0
  end

  # Only allow a trusted parameter "white list" through.
  def todo_params
    params.permit(:title, :order, :completed)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  layout false

  # GET /lists/1
  def show
    @list = List.find(params[:id])
    render layout: false
  end

  # POST /lists
  def create
    session[:caliper_api_key] = params[:caliper_api_key]
    redirect_to List.create!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/lists/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo Backbone Rails Example</title>
</head>
<body>

<form action="<%= lists_path %>" method="post">
  Enter Your Caliper API Key:
  <input type="text" name="caliper_api_key" value="<%= session[:caliper_api_key] %>">
  <input type="submit" value="Start a new list!">
</form>

<a href="https://github.com/caliper-io/todo-backbone-rails"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>

</body>
</html>

app/views/lists/show.html.erb
<!-- This is from https://github.com/tastejs/todomvc/blob/gh-pages/architecture-examples/backbone/index.html -->

<!doctype html>
<html lang="en" data-framework="backbonejs">
  <head>
    <script type="text/javascript">
      var Caliper = {
        config: {
          apiKey: "<%= session[:caliper_api_key] %>",
          debug: true,
          disableAjaxFilter: true,
          minDuration: 10
        }
      };
    </script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Backbone.js • TodoMVC</title>
    <link rel="stylesheet" href="/bower_components/todomvc-common/base.css">
  </head>
  <body>
    <section id="todoapp">
      <header id="header">
        <h1>todos</h1>
        <input id="new-todo" placeholder="What needs to be done?" autofocus>
      </header>
      <section id="main">
        <input id="toggle-all" type="checkbox">
        <label for="toggle-all">Mark all as complete</label>
        <ul id="todo-list"></ul>
      </section>
      <footer id="footer"></footer>
    </section>
    <footer id="info">
      <p>Double-click to edit a todo</p>
      <p>Written by <a href="https://github.com/addyosmani">Addy Osmani</a></p>
      <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
    </footer>
    <script type="text/template" id="item-template">
      <div class="view">
        <input class="toggle" type="checkbox" <%%= completed ? 'checked' : '' %>>
        <label><%%- title %></label>
        <button class="destroy"></button>
      </div>
      <input class="edit" value="<%%- title %>">
    </script>
    <script type="text/template" id="stats-template">
      <span id="todo-count"><strong><%%= remaining %></strong> <%%= remaining === 1 ? 'item' : 'items' %> left</span>
      <ul id="filters">
        <li>
          <a class="selected" href="#/">All</a>
        </li>
        <li>
          <a href="#/active">Active</a>
        </li>
        <li>
          <a href="#/completed">Completed</a>
        </li>
      </ul>
      <%% if (completed) { %>
      <button id="clear-completed">Clear completed (<%%= completed %>)</button>
      <%% } %>
    </script>
    <script type="application/javascript">
      window.TodoListId = '<%= @list.id %>';
    </script>
    <script src="/bower_components/jquery/jquery.js"></script>
    <script src="/bower_components/underscore/underscore.js"></script>
    <script src="/bower_components/backbone/backbone.js"></script>
    <script type="text/javascript" src="//d2yr92gots5pio.cloudfront.net/caliper.backbone-<%= params[:v] || "latest" %>.min.js"></script>
    <script src="/js/models/todo.js"></script>
    <script src="/js/collections/todos.js"></script>
    <script src="/js/views/todos.js"></script>
    <script src="/js/views/app.js"></script>
    <script src="/js/routers/router.js"></script>
    <script src="/js/app.js"></script>

    <a href="https://github.com/caliper-io/todo-backbone-rails"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>

  </body>
</html>